In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras

2022-08-16 11:23:35.835170: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-16 11:23:35.835256: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/abbas/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

In [3]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
x_train.shape

(60000, 28, 28)

In [8]:
x_test.shape

(10000, 28, 28)

In [12]:
x_test.ndim

2

In [17]:
y_train.shape


(60000,)

In [18]:
x_train=x_train/255
x_test=x_test/255

In [19]:
x_train=x_train.reshape(len(x_train),28*28)
x_test=x_test.reshape(len(x_test),28*28)

In [28]:
model=keras.Sequential([
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss="sparse_categorical_crossentropy",
    metrics=['accuracy']
)
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2733 - accuracy: 0.9222
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1248 - accuracy: 0.9628
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0876 - accuracy: 0.9733
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0658 - accuracy: 0.9805
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0515 - accuracy: 0.9842


In [29]:
model.evaluate(x_train,y_train)

1875/1875 [==============================] - 2s 1ms/step - loss: 0.0445 - accuracy: 0.9867


[0.044455140829086304, 0.9866666793823242]

In [30]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0892 - accuracy: 0.9726


[0.0892295315861702, 0.972599983215332]

In [26]:
pred=model.predict(x_test)
pred

array([[1.6047247e-02, 3.2414368e-07, 3.6898527e-02, ..., 9.9973035e-01,
        8.2462959e-02, 5.5558068e-01],
       [4.9901497e-01, 8.0125779e-03, 9.9924594e-01, ..., 2.7465749e-12,
        2.4207471e-01, 3.5184469e-09],
       [4.3753351e-04, 9.9425358e-01, 5.9176451e-01, ..., 1.8672712e-01,
        3.9782605e-01, 5.0683092e-02],
       ...,
       [2.4711940e-06, 4.5975526e-06, 7.2034501e-04, ..., 2.3096503e-01,
        5.2500182e-01, 7.5234300e-01],
       [1.2348026e-04, 2.2058090e-04, 1.3128118e-04, ..., 7.7015786e-05,
        7.5578159e-01, 1.0616117e-04],
       [9.6469102e-03, 4.9749943e-10, 2.0652357e-01, ..., 9.8748295e-08,
        4.2279172e-04, 1.4269559e-06]], dtype=float32)